configure: set abs_srcdir

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25,7 +25,7 @@ PIC_FLAGS=-fPIC
 show_help=no
 progname=$0
 
-subst_vars="CC CXX GNATMAKE CFLAGS LDFLAGS build srcdir prefix backend libdirsuffix libdirreverse gcc_src_dir llvm_config llvm_be backtrace_lib build_mode EXEEXT SOEXT PIC_FLAGS default_pie"
+subst_vars="CC CXX GNATMAKE CFLAGS LDFLAGS build srcdir abs_srcdir prefix backend libdirsuffix libdirreverse gcc_src_dir llvm_config llvm_be backtrace_lib build_mode EXEEXT SOEXT PIC_FLAGS default_pie"
 
 # Find srcdir
 srcdir=`dirname $progname`
@@ -94,7 +94,27 @@ EOF
 exit 0
 fi
 
+# Set abs_srcdir (absolute srcdir)
+case $srcdir in
+    /*) abs_srcdir=$srcdir;;
+    *) abs_srcdir=`pwd`/$srcdir ;;
+esac
+
 # Sanity checks
+# Check srcdir
+pat="2019802090ed76fc5c54cec58f22a2c1"
+if ! grep $pat $srcdir/configure > /dev/null 2>&1; then
+    echo "Incorrect srcdir; try with --srcdir=xx"
+    echo "srcdir=$srcdir"
+    exit 1
+fi
+
+if ! cmp $srcdir/configure $abs_srcdir/configure > /dev/null 2>&1; then
+    echo "Cannot compute absolute source dir (or incorrect srcdir)"
+    echo "srcdir=$srcdir"
+    echo "abs_srcdir=$abs_srcdir"
+    exit 1
+fi
 # Check that gnatmake exists
 if ! $GNATMAKE --version >/dev/null 2>&1; then
     echo "Sorry, you need GNAT to build GHDL.  See the README"
