Investigate LLVM (gcc) versions in Ubuntu.

diff --git a/.github/workflows/Build-Ubuntu.yml b/.github/workflows/Build-Ubuntu.yml
--- a/.github/workflows/Build-Ubuntu.yml
+++ b/.github/workflows/Build-Ubuntu.yml
@@ -79,7 +79,7 @@ jobs:
             APT_ARGS="$APT_ARGS libgmp-dev libmpfr-dev libmpc-dev libgettextpo-dev flex"
           else
             echo "Unknown backend!"
-            exit
+            exit 1
           fi
           echo "APT_ARGS=$APT_ARGS"
 
@@ -117,7 +117,7 @@ jobs:
             CONFIG_ARGS="--with-gcc=../../gcc-srcs"
           else
             echo "Unknown backend!"
-            exit
+            exit 1
           fi
           echo "CONFIG_ARGS=$CONFIG_ARGS"
 
@@ -172,27 +172,54 @@ jobs:
 
       - name: 📋 Write requirements file
         run: |
-          ls -lAh
-          if ${{ endsWith(inputs.ubuntu_image, '22.04') }}; then
-            echo "libgnat-10" >> ubuntu.requirements
-          elif ${{ endsWith(inputs.ubuntu_image, '24.04') }}; then
-            echo "libgnat-13" >> ubuntu.requirements
+          GCC_VERSION="$(gcc --version | grep gcc)"
+          echo "gcc --version:         ${GCC_VERSION}"
+          regex='gcc \((.*?)\) ([0-9]+)\.([0-9]+)\.([0-9]+)'
+          if [[ "${GCC_VERSION}" =~ $regex ]]; then
+            # echo "GCC major version: ${BASH_REMATCH[2]}"
+            GCC_MAJOR_VERSION=${BASH_REMATCH[2]}
           else
-            echo "Unsupported Ubuntu image."
-            exit
+            echo "Can't parse GCC's major version!"
+            exit 1
           fi
 
-          if ${{ startsWith(inputs.backend, 'llvm') }}; then
-            echo "gcc" >> ubuntu.requirements
-            if ${{ endsWith(inputs.ubuntu_image, '22.04') }}; then
-              echo "libllvm15" >> ubuntu.requirements
-            elif ${{ endsWith(inputs.ubuntu_image, '24.04') }}; then
-              echo "libllvm18" >> ubuntu.requirements
-            else
-              echo "Unsupported Ubuntu image."
-              exit
-            fi
+          GNAT_VERSION="$(gnatls --version | grep GNATLS)"
+          echo "gnatls --version:      ${GNAT_VERSION}"
+          regex='GNATLS ([0-9]+)\.([0-9]+)\.([0-9]+)'
+          if [[ "${GNAT_VERSION}" =~ $regex ]]; then
+            # echo "GNAT major version: ${BASH_REMATCH[1]}"
+            GNAT_MAJOR_VERSION=${BASH_REMATCH[1]}
+          else
+            echo "Can't parse GNAT's major version!"
+            exit 1
           fi
+
+          # Common GHDL dependencies
+          echo "libgnat-${GNAT_MAJOR_VERSION}" >> ubuntu.requirements
+
+          # LLVM specific dependencies
+          if ${{ startsWith(inputs.backend, 'llvm') }}; then
+            LLVM_VERSION="$(llvm-config --version)"
+            echo "llvm-config --version: ${LLVM_VERSION}"
+            regex='([0-9]+)\.([0-9]+)\.([0-9]+)'
+            if [[ "${LLVM_VERSION}" =~ $regex ]]; then
+              # echo "LLVM major version: ${BASH_REMATCH[1]}"
+              LLVM_MAJOR_VERSION=${BASH_REMATCH[1]}
+            else
+              echo "Can't parse LLVM's major version!"
+              exit 1
+            fi
+
+            # echo "gcc-${GCC_MAJOR_VERSION}" >> ubuntu.requirements
+            echo "gcc" >> ubuntu.requirements
+            echo "libc-dev" >> ubuntu.requirements
+            echo "zlib1g-dev" >> ubuntu.requirements
+            echo "libllvm${LLVM_MAJOR_VERSION}" >> ubuntu.requirements
+          fi
+
+          echo -e "\e[36mCollected requirements:\e[0m"
+          cat ubuntu.requirements | while read -r line; do echo -e "\e[36m  ${line}\e[0m"; done
+
           sudo cp ubuntu.requirements ./install
 
       - name: Run 'sanity' from testsuite
