Move symbolic link from Dash to Bash.

diff --git a/.github/workflows/Test-Docker.yml b/.github/workflows/Test-Docker.yml
--- a/.github/workflows/Test-Docker.yml
+++ b/.github/workflows/Test-Docker.yml
@@ -39,6 +39,18 @@ jobs:
 
       - name: Version check
         run: |
+          ERRORS=0
+
+          printf "Checking active shell ...\n"
+          activeShell=$(readlink /proc/$$/exe)
+          if [[ "$activeShell" == "$(which bash)" ]]; then
+            printf "  Shell is Bash (%s - version %s)  ${ANSI_GREEN}[OK]${ANSI_NOCOLOR}\n" "$activeShell" "$(/bin/bash --version | head -n 1)"
+          else
+            printf "  Shell is %s ${ANSI_RED}[FAILED]${ANSI_NOCOLOR}\n" "$activeShell"
+            printf "::error title=%s::%s\n" "Test-Docker" "Active shell is not Bash. (actual: ${activeShell} != expected: $(which bash))"
+            ERROR=1
+          fi
+
           printf "BASH_VERSION=%s\n" "${BASH_VERSION}"
           printf "which ghdl: %s\n" "$(which ghdl)"
 
@@ -47,7 +59,8 @@ jobs:
             printf "${ANSI_LIGHT_GREEN}%s${ANSI_NOCOLOR}\n" "[PASSED]"
           else
             printf "${ANSI_LIGHT_RED}%s${ANSI_NOCOLOR}\n" "[FAILED]"
-            printf "::warning title=%s::%s\n" "Test-Docker" "GHDL_VERSION doesn't match. (actual: ${GHDL_VERSION} != expected: ${{ inputs.ghdl_version }})"
+            printf "::error title=%s::%s\n" "Test-Docker" "GHDL_VERSION doesn't match. (actual: ${GHDL_VERSION} != expected: ${{ inputs.ghdl_version }})"
+            ERROR=1
           fi
 
           printf "Verify GHDL_BACKEND=%s " "${GHDL_BACKEND}"
@@ -55,7 +68,8 @@ jobs:
             printf "${ANSI_LIGHT_GREEN}%s${ANSI_NOCOLOR}\n" "[PASSED]"
           else
             printf "${ANSI_LIGHT_RED}%s${ANSI_NOCOLOR}\n" "[FAILED]"
-            printf "::warning title=%s::%s\n" "Test-Docker" "GHDL_BACKEND doesn't match. (actual: ${GHDL_BACKEND} != expected: ${{ inputs.ghdl_backend }})"
+            printf "::error title=%s::%s\n" "Test-Docker" "GHDL_BACKEND doesn't match. (actual: ${GHDL_BACKEND} != expected: ${{ inputs.ghdl_backend }})"
+            ERROR=1
           fi
 
           expected="${{ inputs.ghdl_version }}"
@@ -64,10 +78,13 @@ jobs:
             printf "${ANSI_LIGHT_GREEN}%s${ANSI_NOCOLOR}\n" "[PASSED]"
           else
             printf "${ANSI_LIGHT_RED}%s${ANSI_NOCOLOR}\n" "[FAILED]"
-            printf "::warning title=%s::%s\n" "Test-Docker" "GHDL version doesn't match. (actual: $(ghdl --version | head -n 1) =~ expected: ${{ inputs.ghdl_version }})"
+            printf "::error title=%s::%s\n" "Test-Docker" "GHDL version doesn't match. (actual: $(ghdl --version | head -n 1) =~ expected: ${{ inputs.ghdl_version }})"
+            ERROR=1
 
             ghdl --version
           fi
+
+          exit $ERROR
 
       - name: Run tests in testsuite
         run: |
